### ISSUE TITLE
KeyError: `noise_delta_skip`

### ISSUE THREAD

**Issue by Athanaseus** [Fil8/SHARPener#17]
```run_sharpener -c  sharpener_default.yml
/usr/local/lib/python2.7/dist-packages/astroquery/sdss/__init__.py:29: UserWarning: Experimental: SDSS has not yet been refactored to have its API match the rest of astroque
ry (but it's nearly there).
  warnings.warn("Experimental: SDSS has not yet been refactored to have its API "
Setup logger with lib.setup_logger()
## Load parameter file
## Load parameter file ... Done (0.01s)
## Extract HI spectra from cube
Loading ./scratch/output/pybdsm_continuum_image1.lsm.html: Tigger sky model
# Total number of sources:      10
# Sources below threshold:      0
# Sources outside f.o.v.:       0
# Sources to analyze:           10

Traceback (most recent call last):
  File "/usr/local/bin/run_sharpener", line 137, in <module>
    spectra = spec_ex.abs_ex(spar.cfg_par)
  File "/usr/local/lib/python2.7/dist-packages/sharpener/sharp_modules/spec_ex.py", line 190, in abs_ex
    rInt = cfg_par['spec_ex']['noise_delta_skip']
KeyError: 'noise_delta_skip'

```

**Comment by Fil8** [comment]
yes found the error, discrepancy between code and default config.
